# Generated by Django 4.0.1 on 2022-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='deate_created',
            new_name='date_created',
        ),
    ]
