# Generated by Django 4.0.1 on 2022-01-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_rename_deate_created_book_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deate_created',
            new_name='date_created',
        ),
    ]
