# Generated by Django 4.0.1 on 2022-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='person.png', null=True, upload_to=''),
        ),
    ]
